version: "3"

services:
  code-server:
    image: codercom/code-server:latest
    container_name: code-server
    restart: unless-stopped
    environment:
      - PASSWORD=password #自行更改
      - SUDO_PASSWORD=sudopassword #自行更改
    volumes:
      - ${volumes:?err}/code-server/config:/config
      - ${volumes:?err}/code-server/data:/home/coder
      - ${volumes:?err}/code-server/apt:/etc/apt
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080 #自行更改
    privileged: true 