version: '3'
 
services:
  db:
    # mariadb和mysql二选一即可
    image: mariadb:latest
    container_name: nextcloud-fpm-db
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW --max-binlog-size=200M --expire-logs-days=2 # 优化mysql配置
    restart: unless-stopped
    volumes:
      - ${volumes:?err}/nextcloud/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=nextcloud
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - default
 
  cache:
    image: redis:latest
    container_name: nextcloud-fpm-cache
    restart: unless-stopped
    expose:
     - "6379" # 可用此默认。因为这是暴露而不是映射
    volumes:
     - ${volumes:?err}/nextcloud/cache:/data
    networks:
      - default
 
  app:
    image: nextcloud:fpm
    container_name: nextcloud-fpm-app
    restart: unless-stopped
    volumes:
      - ${volumes:?err}/nextcloud/app:/var/www/html
      - ${custom_path:?err}/www.conf:/usr/local/etc/php-fpm.d/www.conf
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=cache
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    depends_on:
      - db
      - cache
    networks:
      - default
 
  cron:
    image: nextcloud:fpm
    container_name: nextcloud-fpm-cron
    restart: unless-stopped
    volumes:
      - ${volumes:?err}/nextcloud/app:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - cache
    networks:
      - default
 
  web:
    image: songhaorun/nextcloud-fpm-web
    build:
      context: ${web_build_path:?err}
      cache_from:
        - nginx:alpine
    container_name: nextcloud-fpm-web
    restart: unless-stopped
    ports:
      - 80:80 #自行更改
    volumes:
      - ${volumes:?err}/nextcloud/app:/var/www/html
    depends_on:
      - app
    networks:
      - default
 
networks:
  default:
    name: nextcloud-fpm