version: "3.6"
services:
  app:
    container_name: portainer 
    image: portainer/portainer-ce:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${volumes:?err}/portainer/data:/data/
    ports:
      - 9443:9443 #自行更改
    privileged: true